image: node:11.6.0-alpine

before_script:
  - pwd
  - ls -l

stages:
  - deploy
  - build
  - quality

build:
  stage: build
  script: yarn
  artifacts:
    paths:
      - node_modules
    expire_in: 1 day

lint:
  stage: quality
  script: yarn lint

unit_test:
  stage: quality
  script: yarn test

coverage_test:
  stage: quality
  script: yarn test_coverage

deploy_to_production:
  stage: deploy
  before_script:
    - apk add curl
    - echo $CI_COMMIT_SHA
  script:
    - git checkout production
    - git merge origin/master
    - git reset --hard $CI_COMMIT_SHA
    - git push -f
  only: 
    - master
