image: node:11.6.0-alpine

before_script:
  - pwd
  - ls -l

stages:
  - build
  - quality
  - deploy

build:
  stage: build
  script: yarn
  artifacts:
    paths:
      - node_modules
    expire_in: 1 day

lint:
  stage: quality
  script: yarn lint

unit_test:
  stage: quality
  script: yarn test

coverage_test:
  stage: quality
  script: yarn test_coverage

deploy_to_production:
  stage: deploy
  before_script:
    - apk add curl
  script:
    - curl -X POST -d {} https://api.netlify.com/build_hooks/5c33c138e6c7ac5213342f93
  only: 
    - master
    - feature/deploy_via_ci
